[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "PolyU Survival"
authors = [{name = "Leming Shen", email = "zju.slm@gmail.com"}]
dynamic = ["version", "description"]
